### PR TITLE
Adding a python soloution and a haskell soloution

### PR DESCRIPTION
**Pull request by Jotrorox**

### CODE REVIEW

**Comment by ImmutableVariable** [comment]
This prompt did not ask for code golfed versions, along with this, you did not provide a commented version as is with the only code golfed challenged, along with not following the format. If the prompt does not ask for the smallest solution, do not send it as its unreadable and lacks a commented code example. I would just submit the last example.

**Comment by ImmutableVariable** [comment]
basically.
- if it does not ask for a code golfed solution, don't send it, its supposed to be learning platform, i prefer optimized solutions over the shortest possible code
  - if the prompt asks for code golfed version, it should include comments that accurately describes each step.
  - the only code golf solution is happy numbers, which is so easy it made sense, otherwise the prompt would be too easy. Feel free to do this on your own, but as its mainly designed for beginners/intermediates which don't care about your smallest solution generally
- most people don't want that solution as its fairly useless in the real world and there is not much to learn from it

**Comment by ImmutableVariable** [comment]
CONTRIBUTERS has been updated...

```
- DO NOT submit code golf solutions unless the prompt EXPLICITLY asks for it.
    - Why?
        - Code golfed solutions are NOT beginner friendly and are NOT helpful for most people. 
        - They don't teach good programming practices and are often hard to read or understand. 
        - They might also be less efficent than other solutions as you prioritize shortcode over efficency . 
    - Feel free to do it on your own, just dont submit it offically to the repository unless the prompt EXPLICITLY asks for it.
    - IF the prompt asks for it, you MUST provide a non golfed solution with comments explaining the golfed solution.
    - If you submit a golfed solution without a non golfed solution (TO A PROMPT THAT ASKS FOR IT), it will be rejected.
```

**Comment by Jotrorox** [comment]
I'm sorry, I will update my solutions accordingly

**Pull request closed without merging**
